version: "3.8"

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      PORT: 3333
      HOST: 0.0.0.0
    # Remove volume mapping for production-like testing
    # volumes:
    #   - .:/app
    restart: unless-stopped
